### ISSUE TITLE
compilation error: undefined function from_file/1

### ISSUE THREAD

**Issue by stephenmoloney** [ma2gedev/breadcrumble_ex#1]
``` shell
~/breadcrumble_ex_$ mix compile
==> power_assert
Compiled lib/power_assert.ex
Compiled lib/power_assert/assertion_eraser.ex
Compiled lib/power_assert/ast.ex
Compiled lib/power_assert/case_template.ex
Compiled lib/power_assert/ex_unit_case.ex
Compiled lib/power_assert/ex_unit_case_template.ex
Compiled lib/power_assert/assertion.ex
Compiled lib/power_assert/debug.ex
Generated power_assert app
==> plug
Compiled lib/plug.ex
Compiled lib/plug/adapters/cowboy.ex
Compiled lib/plug/builder.ex
Compiled lib/plug/conn/adapter.ex
Compiled lib/plug/conn/cookies.ex
Compiled lib/plug/conn/status.ex
Compiled lib/plug/conn/unfetched.ex
Compiled lib/plug/conn/query.ex
Compiled lib/plug/crypto.ex
Compiled lib/plug/conn/wrapper_error.ex
Compiled lib/plug/conn/utils.ex
Compiled lib/plug/crypto/key_generator.ex
Compiled lib/plug/crypto/message_encryptor.ex
Compiled lib/plug/crypto/message_verifier.ex
Compiled lib/plug/error_handler.ex
Compiled lib/plug/html.ex
Compiled lib/plug/logger.ex
Compiled lib/plug/method_override.ex
Compiled lib/plug/head.ex
Compiled lib/plug/exceptions.ex
Compiled lib/plug/adapters/translator.ex
Compiled lib/plug/adapters/test/conn.ex
Compiled lib/plug/adapters/cowboy/handler.ex
Compiled lib/plug/request_id.ex
Compiled lib/plug/router.ex
Compiled lib/plug/parsers.ex
Compiled lib/plug/parsers/urlencoded.ex
Compiled lib/plug/router/utils.ex
Compiled lib/plug/conn.ex
Compiled lib/plug/parsers/json.ex
Compiled lib/plug/session.ex
Compiled lib/plug/csrf_protection.ex
Compiled lib/plug/session/store.ex
Compiled lib/plug/session/ets.ex
Compiled lib/plug/ssl.ex
Compiled lib/plug/session/cookie.ex
Compiled lib/plug/supervisor.ex
Compiled lib/plug/debugger.ex
Compiled lib/plug/test.ex
Compiled lib/plug/static.ex
Compiled lib/plug/parsers/multipart.ex
Compiled lib/plug/adapters/cowboy/conn.ex
Compiled lib/plug/upload.ex
Compiled lib/plug/mime.ex
Generated plug app
==> breadcrumble
Compiled lib/breadcrumble.ex

== Compilation error on file lib/mix/tasks/breadcrumble.gen.views.ex ==
** (CompileError) lib/mix/tasks/breadcrumble.gen.views.ex:22: undefined function from_file/1
    (mix) expanding macro: Mix.Generator.embed_text/2
    lib/mix/tasks/breadcrumble.gen.views.ex:22: Mix.Tasks.Breadcrumble.Gen.Views (module)
    (elixir) lib/kernel/parallel_compiler.ex:100: anonymous fn/4 in Kernel.ParallelCompiler.spawn_compilers/8
```

**Comment by stephenmoloney** [comment]
Possible fix.
[pull request link](https://github.com/ma2gedev/breadcrumble_ex/pull/2).

**Comment by wicliff** [comment]
Just had the same issue. Works fine on Elixir 1.0.5. Problem is with Elixir 1.1.1

**Comment by ma2gedev** [comment]
@stephenmoloney 
Thank you for reporting. I merged your pull request.

**Comment by ma2gedev** [comment]
And just published [version 1.0.1](https://hex.pm/packages/breadcrumble) to hex.pm. :rocket:
